FROM python:3.13-alpine3.21

RUN apk add --no-cache shadow

# Add a group with GID 1000
RUN groupadd -g 1000 pythonuser

# Add a user with UID 1000, GID 1000, and a home directory
RUN useradd -m -u 1000 -g 1000 pythonuser

# Add the user to a group (GID 1000)
RUN usermod -aG pythonuser pythonuser

# Switch to the new user
USER pythonuser

# Add user directory
WORKDIR /home/pythonuser

